{
  imports = [
    ./modules/system/core.nix
    ./modules/system/hardware.nix
    ./modules/system/networking.nix
    ./modules/system/packages.nix
    ./modules/system/users.nix
    ./modules/services/minecraft.nix
    ./modules/services/navidrome.nix
    ./modules/services/monitoring.nix
    ./modules/services/adguard.nix
    ./modules/services/unbound.nix
    ./modules/services/syncthing.nix
    ./modules/services/dashboard.nix
    ./modules/services/media.nix
    ./modules/services/extras.nix
    ./modules/services/openclaw.nix
  ];
}
