########################################
# Hypridle — idle handling + power automation
########################################

general {
    lock_cmd = hyprlock -c /home/karimkandil/.dotfiles/config/hypr/hyprlock.conf
    unlock_cmd = hyprctl dispatch dpms on
    before_sleep_cmd = hyprlock -c /home/karimkandil/.dotfiles/config/hypr/hyprlock.conf && hyprctl dispatch dpms off
    after_sleep_cmd = hyprctl dispatch dpms on

    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
    inhibit_sleep = 3
}

listener {
    timeout = 300
    on-timeout = hyprlock -c /home/karimkandil/.dotfiles/config/hypr/hyprlock.conf
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
    on-resume = hyprctl dispatch dpms on
}
