########################################
# HYPRLAND MODULES
########################################

source = ~/.dotfiles/config/hypr/modules/monitors.conf
source = ~/.dotfiles/config/hypr/modules/keybinds.conf
source = ~/.dotfiles/config/hypr/modules/rules.conf
source = ~/.dotfiles/config/hypr/modules/appearance.conf
source = ~/.dotfiles/config/hypr/modules/wal-colors.conf
source = ~/.dotfiles/config/hypr/modules/autostart.conf
source = ~/.dotfiles/config/hypr/modules/env.conf
source = ~/.dotfiles/config/hypr/modules/input.conf
