#!/usr/bin/env bash

# Prevent duplicate instances (common after reloads/manual starts)
LOCK_FILE="$HOME/.cache/walstart.lock"
exec 9>"$LOCK_FILE"
if ! flock -n 9; then
    echo "walstart already running, exiting."
    exit 0
fi

# Directory containing your wallpapers
WALL_DIR="$HOME/Walls/All/"

# History file to store used wallpapers
HISTORY_FILE="$HOME/.cache/wal_history"

# Time between wallpaper changes (seconds)
INTERVAL=500

# Start swww daemon if it's not already running
if ! pgrep -x "swww-daemon" >/dev/null 2>&1; then
    swww-daemon >/dev/null 2>&1 &
    sleep 1
fi

# Create history file if it doesn't exist
touch "$HISTORY_FILE"

change_wallpaper() {
    # Get all wallpapers
    ALL_WALLPAPERS=($(find "$WALL_DIR" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \)))

    # If no image found, exit
    [ ${#ALL_WALLPAPERS[@]} -eq 0 ] && echo "No wallpapers found in $WALL_DIR" && exit 1

    # Get used wallpapers
    USED_WALLPAPERS=($(cat "$HISTORY_FILE"))

    # Get unused wallpapers
    UNUSED_WALLPAPERS=()
    for wallpaper in "${ALL_WALLPAPERS[@]}"; do
        if ! [[ " ${USED_WALLPAPERS[@]} " =~ " ${wallpaper} " ]]; then
            UNUSED_WALLPAPERS+=("$wallpaper")
        fi
    done

    # If all wallpapers have been used, clear the history
    if [ ${#UNUSED_WALLPAPERS[@]} -eq 0 ]; then
        echo "All wallpapers have been used. Resetting history."
        > "$HISTORY_FILE"
        UNUSED_WALLPAPERS=("${ALL_WALLPAPERS[@]}")
    fi

    # Pick a random image from the unused wallpapers
    IMG="${UNUSED_WALLPAPERS[RANDOM % ${#UNUSED_WALLPAPERS[@]}]}"

    # Set wallpaper with swww (you can tweak transition options)
    swww img "$IMG" --outputs "HDMI-A-1,DP-1" --transition-type fade --transition-duration 1 

    # Generate colorscheme with wal based on the current wallpaper
    wal -i "$IMG"

    # Source the pywal colors
    source "${HOME}/.cache/wal/colors.sh"

    # Generate Hyprland color overrides from pywal
    # Pick the most vibrant pywal color for active border.
    pick_most_vibrant_pywal_color() {
        local best="#cba6f7"
        local best_score=-1

        for i in $(seq 1 15); do
            local var="color${i}"
            local c="${!var}"
            [[ -z "$c" ]] && continue

            c="${c#\#}"
            [[ ${#c} -ne 6 ]] && continue

            local r=$((16#${c:0:2}))
            local g=$((16#${c:2:2}))
            local b=$((16#${c:4:2}))

            local max=$r
            (( g > max )) && max=$g
            (( b > max )) && max=$b

            local min=$r
            (( g < min )) && min=$g
            (( b < min )) && min=$b

            local sat=$((max - min))
            local score=$((sat * 3 + max))

            if (( score > best_score )); then
                best_score=$score
                best="#${c}"
            fi
        done

        echo "$best"
    }

    WAL_ACTIVE="$(pick_most_vibrant_pywal_color)"
    WAL_INACTIVE="${color8:-#45475a}"

    cat > "${HOME}/.dotfiles/config/hypr/modules/wal-colors.conf" <<EOF
########################################
# AUTO-GENERATED BY walstart.sh (pywal)
# Do not edit manually.
########################################
general {
    col.active_border = rgba(${WAL_ACTIVE#\#}ee)
    col.inactive_border = rgba(${WAL_INACTIVE#\#}aa)
}
EOF

    # Add the new wallpaper to the history
    echo "$IMG" >> "$HISTORY_FILE"
}

if [[ "$1" == "--force" ]]; then
    change_wallpaper
    exit 0
fi

# Infinite loop: shuffle wallpaper and update wal
while true; do
    change_wallpaper
    # Wait before next wallpaper
    sleep "$INTERVAL"
done
