########################################
# AUTOSTART APPLICATIONS
# Commands here run once when Hyprland starts.
########################################
exec-once = waybar
exec-once = mako --config /home/karimkandil/.dotfiles/config/mako/config
exec-once = /home/karimkandil/.dotfiles/config/hypr/walstart.sh &
