########################################
# AUTOSTART APPLICATIONS
# Commands here run once when Hyprland starts.
########################################
# exec-once = $terminal
# exec-once = nm-applet &
exec-once = ~/.dotfiles/config/hypr/walstart.sh &
