########################################
# PROGRAM SHORTCUT VARIABLES
# Defines variables for commonly launched applications.
########################################
$terminal = kitty
$fileManager = xplr
$browser = zen
$steam = steam
$menu = rofi -show drun
$editor =  zeditor

########################################
# KEYBINDINGS — HOTKEYS FOR ACTIONS
########################################
$mainMod = SUPER

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, W, exec, kitty -e nmtui
bind = $mainMod, L, exec, $browser
bind = $mainMod, BACKSPACE, killactive,
bind = $mainMod, Q, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, P, exec, prismlauncher
bind = $mainMod, E, exec, kitty -e xplr
bind = $mainMod, G, exec, kitty -e gemini
bind = $mainMod, C, exec, kitty -e codex
bind = $mainMod, Escape, exec, systemctl --user is-active key-glow.service && systemctl --user stop key-glow.service || systemctl --user start key-glow.service
bind = $mainMod, O, exec, $editor
bind = $mainMod, F, fullscreen
bind = $mainMod, V, togglefloating
bind = $mainMod, M, exec, $menu
bind = $mainMod, I, pseudo,
bind = $mainMod, J, togglesplit,

# Skip to next wallpaper
bind = $mainMod, N, exec, /home/karimkandil/.dotfiles/config/hypr/skip-wallpaper.sh

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod CTRL, 1, movetoworkspace, 1
bind = $mainMod CTRL, 2, movetoworkspace, 2
bind = $mainMod CTRL, 3, movetoworkspace, 3
bind = $mainMod CTRL, 4, movetoworkspace, 4
bind = $mainMod CTRL, 5, movetoworkspace, 5
bind = $mainMod CTRL, 6, movetoworkspace, 6
bind = $mainMod CTRL, 7, movetoworkspace, 7
bind = $mainMod CTRL, 8, movetoworkspace, 8
bind = $mainMod CTRL, 9, movetoworkspace, 9
bind = $mainMod CTRL, 0, movetoworkspace, 10

bind = $mainMod, S,togglespecialworkspace, magic
bind = $mainMod CTRL, S, movetoworkspace, special:magic

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
